### ISSUE TITLE
服务器暂无回应，请稍后重试

### ISSUE THREAD

**Issue by leis1** [yunv/wisdomtree#12]
Traceback (most recent call last):
  File "study.py", line 131, in <module>
    save_record(section, lesson['chapterId'], True)
  File "study.py", line 120, in save_record
    rt = post('/student/tutorial/saveLearningRecordByToken', p)
  File "study.py", line 32, in post
    raise ValueError(j['msg'])
ValueError: 服务器暂无回应，请稍后重试

**Comment by yunv** [comment]
Please provide your `userId`.

**Comment by leis1** [comment]
**184413627**
