### ISSUE TITLE
登录状态正常并获取到课程，按下Y键确认开始后，返回错误参数

### ISSUE THREAD

**Issue by massger** [yunv/wisdomtree#17]
Traceback (most recent call last):
  File "study.py", line 132, in <module>
    save_record(section, lesson, True)
  File "study.py", line 121, in save_record
    rt = post('/student/tutorial/saveLearningRecordByToken', p)
  File "study.py", line 27, in post
    j = r.json()
  File "F:\Python36\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "F:\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "F:\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "F:\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by xyggaka** [comment]
遇到同样的问题，请求大佬快快解决。。。py奉上

**Comment by chenshiforever** [comment]
> 遇到同样的问题，请求大佬快快解决。。。py奉上

其实可以根据大佬的博客，学习脱壳+抓包+py，然后就解决了，ps：接口名字改了很多，内容没太大变化

**Comment by yunowo** [comment]
> > 遇到同样的问题，请求大佬快快解决。。。py奉上
> 
> 其实可以根据大佬的博客，学习脱壳+抓包+py，然后就解决了，ps：接口名字改了很多，内容没太大变化

你怎么不提交 Pull Request...
